const USER_TYPES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  RETAILER_MANAGER: "RETAILER_MANAGER",
  RETAILER_ADMIN: "RETAILER_ADMIN",
  MANUFACTURER_ADMIN: "MANUFACTURER_ADMIN",
  DISTRIBUTOR_ADMIN: "DISTRIBUTOR_ADMIN",
  AGRONOMIST: "AGRONOMIST",
  CUSTOMER: "CUSTOMER"
};

module.exports = { USER_TYPES };
