const express = require('express');
const Routes = require('./routes/');
const router = express();
router.use('/auth', Routes.auth);
router.use('/retailer', Routes.retailer);
router.use('/agronomist', Routes.agronomist);
router.use('/manufacturer', Routes.manufacturer);
router.use('/company', Routes.company);
router.use('/document', Routes.document);
router.use('/category', Routes.category);
module.exports = router;