const express = require('express');
const Routes = require('./routes/');
const router = express();
router.use('/auth', Routes.auth);
router.use('/retailer', Routes.retailer);
router.use('/agronomist', Routes.agronomist);
router.use('/manufacturer', Routes.manufacturer);
router.use('/company', Routes.company);
router.use('/document', Routes.document);
router.use('/category', Routes.category);
router.use('/product', Routes.product);
router.use('/inventory', Routes.inventory);
router.use('/order', Routes.order);
module.exports = router;
